// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `heatmap.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package jderobot;

public interface HeatmapPrx extends Ice.ObjectPrx
{
    public HeatmapData getHeatmapData();

    public HeatmapData getHeatmapData(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getHeatmapData();

    public Ice.AsyncResult begin_getHeatmapData(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getHeatmapData(Ice.Callback __cb);

    public Ice.AsyncResult begin_getHeatmapData(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getHeatmapData(Callback_Heatmap_getHeatmapData __cb);

    public Ice.AsyncResult begin_getHeatmapData(java.util.Map<String, String> __ctx, Callback_Heatmap_getHeatmapData __cb);

    public HeatmapData end_getHeatmapData(Ice.AsyncResult __result);

    public HeatmapInfo getHeatmapInfo();

    public HeatmapInfo getHeatmapInfo(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getHeatmapInfo();

    public Ice.AsyncResult begin_getHeatmapInfo(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getHeatmapInfo(Ice.Callback __cb);

    public Ice.AsyncResult begin_getHeatmapInfo(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getHeatmapInfo(Callback_Heatmap_getHeatmapInfo __cb);

    public Ice.AsyncResult begin_getHeatmapInfo(java.util.Map<String, String> __ctx, Callback_Heatmap_getHeatmapInfo __cb);

    public HeatmapInfo end_getHeatmapInfo(Ice.AsyncResult __result);

    public Pose3DData getDronePose();

    public Pose3DData getDronePose(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDronePose();

    public Ice.AsyncResult begin_getDronePose(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDronePose(Ice.Callback __cb);

    public Ice.AsyncResult begin_getDronePose(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDronePose(Callback_Heatmap_getDronePose __cb);

    public Ice.AsyncResult begin_getDronePose(java.util.Map<String, String> __ctx, Callback_Heatmap_getDronePose __cb);

    public Pose3DData end_getDronePose(Ice.AsyncResult __result);
}
