// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `heatmap.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package jderobot;

public final class HeatmapPrxHelper extends Ice.ObjectPrxHelperBase implements HeatmapPrx
{
    private static final String __getDronePose_name = "getDronePose";

    public Pose3DData getDronePose()
    {
        return getDronePose(null, false);
    }

    public Pose3DData getDronePose(java.util.Map<String, String> __ctx)
    {
        return getDronePose(__ctx, true);
    }

    private Pose3DData getDronePose(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "getDronePose", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("getDronePose");
                    __delBase = __getDelegate(false);
                    _HeatmapDel __del = (_HeatmapDel)__delBase;
                    return __del.getDronePose(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_getDronePose()
    {
        return begin_getDronePose(null, false, null);
    }

    public Ice.AsyncResult begin_getDronePose(java.util.Map<String, String> __ctx)
    {
        return begin_getDronePose(__ctx, true, null);
    }

    public Ice.AsyncResult begin_getDronePose(Ice.Callback __cb)
    {
        return begin_getDronePose(null, false, __cb);
    }

    public Ice.AsyncResult begin_getDronePose(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getDronePose(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getDronePose(Callback_Heatmap_getDronePose __cb)
    {
        return begin_getDronePose(null, false, __cb);
    }

    public Ice.AsyncResult begin_getDronePose(java.util.Map<String, String> __ctx, Callback_Heatmap_getDronePose __cb)
    {
        return begin_getDronePose(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getDronePose(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getDronePose_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getDronePose_name, __cb);
        try
        {
            __result.__prepare(__getDronePose_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public Pose3DData end_getDronePose(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getDronePose_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            Pose3DDataHolder __ret = new Pose3DDataHolder();
            __is.readObject(__ret);
            __is.readPendingObjects();
            __result.__endReadParams();
            return __ret.value;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __getHeatmapData_name = "getHeatmapData";

    public HeatmapData getHeatmapData()
    {
        return getHeatmapData(null, false);
    }

    public HeatmapData getHeatmapData(java.util.Map<String, String> __ctx)
    {
        return getHeatmapData(__ctx, true);
    }

    private HeatmapData getHeatmapData(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "getHeatmapData", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("getHeatmapData");
                    __delBase = __getDelegate(false);
                    _HeatmapDel __del = (_HeatmapDel)__delBase;
                    return __del.getHeatmapData(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_getHeatmapData()
    {
        return begin_getHeatmapData(null, false, null);
    }

    public Ice.AsyncResult begin_getHeatmapData(java.util.Map<String, String> __ctx)
    {
        return begin_getHeatmapData(__ctx, true, null);
    }

    public Ice.AsyncResult begin_getHeatmapData(Ice.Callback __cb)
    {
        return begin_getHeatmapData(null, false, __cb);
    }

    public Ice.AsyncResult begin_getHeatmapData(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getHeatmapData(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getHeatmapData(Callback_Heatmap_getHeatmapData __cb)
    {
        return begin_getHeatmapData(null, false, __cb);
    }

    public Ice.AsyncResult begin_getHeatmapData(java.util.Map<String, String> __ctx, Callback_Heatmap_getHeatmapData __cb)
    {
        return begin_getHeatmapData(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getHeatmapData(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getHeatmapData_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getHeatmapData_name, __cb);
        try
        {
            __result.__prepare(__getHeatmapData_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public HeatmapData end_getHeatmapData(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getHeatmapData_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            HeatmapDataHolder __ret = new HeatmapDataHolder();
            __is.readObject(__ret);
            __is.readPendingObjects();
            __result.__endReadParams();
            return __ret.value;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __getHeatmapInfo_name = "getHeatmapInfo";

    public HeatmapInfo getHeatmapInfo()
    {
        return getHeatmapInfo(null, false);
    }

    public HeatmapInfo getHeatmapInfo(java.util.Map<String, String> __ctx)
    {
        return getHeatmapInfo(__ctx, true);
    }

    private HeatmapInfo getHeatmapInfo(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "getHeatmapInfo", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("getHeatmapInfo");
                    __delBase = __getDelegate(false);
                    _HeatmapDel __del = (_HeatmapDel)__delBase;
                    return __del.getHeatmapInfo(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_getHeatmapInfo()
    {
        return begin_getHeatmapInfo(null, false, null);
    }

    public Ice.AsyncResult begin_getHeatmapInfo(java.util.Map<String, String> __ctx)
    {
        return begin_getHeatmapInfo(__ctx, true, null);
    }

    public Ice.AsyncResult begin_getHeatmapInfo(Ice.Callback __cb)
    {
        return begin_getHeatmapInfo(null, false, __cb);
    }

    public Ice.AsyncResult begin_getHeatmapInfo(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getHeatmapInfo(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getHeatmapInfo(Callback_Heatmap_getHeatmapInfo __cb)
    {
        return begin_getHeatmapInfo(null, false, __cb);
    }

    public Ice.AsyncResult begin_getHeatmapInfo(java.util.Map<String, String> __ctx, Callback_Heatmap_getHeatmapInfo __cb)
    {
        return begin_getHeatmapInfo(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getHeatmapInfo(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getHeatmapInfo_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getHeatmapInfo_name, __cb);
        try
        {
            __result.__prepare(__getHeatmapInfo_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public HeatmapInfo end_getHeatmapInfo(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getHeatmapInfo_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            HeatmapInfoHolder __ret = new HeatmapInfoHolder();
            __is.readObject(__ret);
            __is.readPendingObjects();
            __result.__endReadParams();
            return __ret.value;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static HeatmapPrx checkedCast(Ice.ObjectPrx __obj)
    {
        HeatmapPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapPrx)
            {
                __d = (HeatmapPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    HeatmapPrxHelper __h = new HeatmapPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static HeatmapPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        HeatmapPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapPrx)
            {
                __d = (HeatmapPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    HeatmapPrxHelper __h = new HeatmapPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static HeatmapPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        HeatmapPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    HeatmapPrxHelper __h = new HeatmapPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static HeatmapPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        HeatmapPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    HeatmapPrxHelper __h = new HeatmapPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static HeatmapPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        HeatmapPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapPrx)
            {
                __d = (HeatmapPrx)__obj;
            }
            else
            {
                HeatmapPrxHelper __h = new HeatmapPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static HeatmapPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        HeatmapPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            HeatmapPrxHelper __h = new HeatmapPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::jderobot::Heatmap"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _HeatmapDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _HeatmapDelD();
    }

    public static void __write(IceInternal.BasicStream __os, HeatmapPrx v)
    {
        __os.writeProxy(v);
    }

    public static HeatmapPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            HeatmapPrxHelper result = new HeatmapPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
