// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `heatmap.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package jderobot;

public final class HeatmapInfoPrxHelper extends Ice.ObjectPrxHelperBase implements HeatmapInfoPrx
{
    public static HeatmapInfoPrx checkedCast(Ice.ObjectPrx __obj)
    {
        HeatmapInfoPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapInfoPrx)
            {
                __d = (HeatmapInfoPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    HeatmapInfoPrxHelper __h = new HeatmapInfoPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static HeatmapInfoPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        HeatmapInfoPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapInfoPrx)
            {
                __d = (HeatmapInfoPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    HeatmapInfoPrxHelper __h = new HeatmapInfoPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static HeatmapInfoPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        HeatmapInfoPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    HeatmapInfoPrxHelper __h = new HeatmapInfoPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static HeatmapInfoPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        HeatmapInfoPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    HeatmapInfoPrxHelper __h = new HeatmapInfoPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static HeatmapInfoPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        HeatmapInfoPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapInfoPrx)
            {
                __d = (HeatmapInfoPrx)__obj;
            }
            else
            {
                HeatmapInfoPrxHelper __h = new HeatmapInfoPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static HeatmapInfoPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        HeatmapInfoPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            HeatmapInfoPrxHelper __h = new HeatmapInfoPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::jderobot::HeatmapInfo"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _HeatmapInfoDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _HeatmapInfoDelD();
    }

    public static void __write(IceInternal.BasicStream __os, HeatmapInfoPrx v)
    {
        __os.writeProxy(v);
    }

    public static HeatmapInfoPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            HeatmapInfoPrxHelper result = new HeatmapInfoPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
