// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `heatmap.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package jderobot;

public final class HeatmapDataPrxHelper extends Ice.ObjectPrxHelperBase implements HeatmapDataPrx
{
    public static HeatmapDataPrx checkedCast(Ice.ObjectPrx __obj)
    {
        HeatmapDataPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapDataPrx)
            {
                __d = (HeatmapDataPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    HeatmapDataPrxHelper __h = new HeatmapDataPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static HeatmapDataPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        HeatmapDataPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapDataPrx)
            {
                __d = (HeatmapDataPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    HeatmapDataPrxHelper __h = new HeatmapDataPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static HeatmapDataPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        HeatmapDataPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    HeatmapDataPrxHelper __h = new HeatmapDataPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static HeatmapDataPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        HeatmapDataPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    HeatmapDataPrxHelper __h = new HeatmapDataPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static HeatmapDataPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        HeatmapDataPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof HeatmapDataPrx)
            {
                __d = (HeatmapDataPrx)__obj;
            }
            else
            {
                HeatmapDataPrxHelper __h = new HeatmapDataPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static HeatmapDataPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        HeatmapDataPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            HeatmapDataPrxHelper __h = new HeatmapDataPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::jderobot::HeatmapData"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _HeatmapDataDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _HeatmapDataDelD();
    }

    public static void __write(IceInternal.BasicStream __os, HeatmapDataPrx v)
    {
        __os.writeProxy(v);
    }

    public static HeatmapDataPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            HeatmapDataPrxHelper result = new HeatmapDataPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
